server:
  port: 8181
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
 
spring:
  application:
    name: APIGateway
    
zuul:
  routes:
    r1:
      path: /story/**
      serviceId: StoryTemplet
    r2:
      path: /user/**
      serviceId: User
    r3:
      path: /userStory/**
      serviceId: UserStory